<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<div class="product-description-container justify">
    <h2><?= _('Description') ?></h2>
    <p class="justify">
    <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
        $block->getProduct(),
        $block->getProduct()->getDescription(),
        'description'
    ) ?>
    </p>
</div>
